version: 2.1
orbs:
  docker: circleci/docker@2.1.1
jobs:
  build:
    working_directory: ~/lc-mate-backend
    docker:
      - image: cimg/go:1.18.3
    steps:
      - checkout
      - docker/install-docker
      - setup_remote_docker:
          version: 20.10.14
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          command: |
            ./gomod.sh
            ./gotest.sh
